server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roombooking?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出

